Added info on readme
Ratismal/UNO pull request #32
Opened 2021-12-21 11:20 UTC by Mte90

Based on: 

* https://www.reddit.com/r/discordapp/comments/89n8lf/does_anyone_know_how_to_use_ratismals_uno_bot/
* https://github.com/Ratismal/UNO/issues/11

2022-01-01 00:30 UTC, Ratismal requested changes
Hey, thanks for making this PR - and sorry it's taken so long for me to get back on this. Just a few request changes before I merge this in.

2022-01-01 00:30 UTC, Ratismal commented on readme.md
> +}
Please move this to a `config.example.json` file in the root directory

2022-01-01 00:30 UTC, Ratismal commented on readme.md
> +}
Please move this to a `config/config.example.json` file

2022-01-01 00:30 UTC, Ratismal commented on readme.md
> +After running `npm install` it is required to migrate the new database (after put the configuration files) and run `npx sequelize-cli db:migrate`.
I'd recommend using the npm script instead, so you don't have to deal with npx.
```suggestion
After running `npm install` it is required to migrate the new database (after put the configuration files) and run `npm run sequelize db:migrate`.
```

2022-01-01 00:30 UTC, Ratismal commented on readme.md
> +Now you can run the bot with `nodejs index.js`.
Please use `node` instead
```suggestion
Now, you can run the bot with `node index.js`.
```

2022-01-01 00:30 UTC, Ratismal commented on readme.md
> +After running `npm install` it is required to migrate the new database (after put the configuration files) and run `npx sequelize-cli db:migrate`.
Additionally, we could make a new run script in package.json to run the migration command directly.

2022-01-03 12:40 UTC, Mte90 commented
Updated :-)

2022-01-10 00:54 UTC, merged